/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ChoseBot extends javax.swing.JFrame {
private MainMenu mainMenu;
    /**
     * Creates new form ChoseBot
     */
    public ChoseBot(MainMenu mainMenu) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.mainMenu = mainMenu;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hardMode = new javax.swing.JButton();
        easyMode = new javax.swing.JButton();
        middleMode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chọn Độ Khó");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        hardMode.setText("Khó");
        hardMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardModeActionPerformed(evt);
            }
        });

        easyMode.setText("Dễ");
        easyMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyModeActionPerformed(evt);
            }
        });

        middleMode.setText("Vừa");
        middleMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(easyMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(middleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hardMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hardMode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(easyMode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // hàm lưu kết quả 
    private int resultMode(){
          int  result = JOptionPane.showConfirmDialog(this, "Bạn có muốn đánh trước không", "Chọn lượt chơi", JOptionPane.YES_NO_OPTION);
            return result;
    }
    // result = 0 thì người chơi đánh trước => X, result = 1 thì ngược lại máy đánh trc
    
    private void easyModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyModeActionPerformed
        // TODO add your handling code here:
          int result = resultMode();
               if (result < 0) {
            return;
        }
          this.dispose();
          this.mainMenu.dispose();
          GameCaroWithAI gameCaroWithAI = new GameCaroWithAI(0, result, this.mainMenu.player);
            
    }//GEN-LAST:event_easyModeActionPerformed

    private void middleModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleModeActionPerformed
        // TODO add your handling code here:
                 int result = resultMode();
                      if (result < 0) {
            return;
        }
                   this.dispose();
                          this.mainMenu.dispose();
                 GameCaroWithAI gameCaroWithAI = new GameCaroWithAI(1,result,mainMenu.player);
    }//GEN-LAST:event_middleModeActionPerformed

    private void hardModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardModeActionPerformed
        // TODO add your handling code here:
              int result = resultMode();
              if (result < 0) {
            return;
        }
                this.dispose();
                       this.mainMenu.dispose();
              GameCaroWithAI gameCaroWithAI = new GameCaroWithAI(3
                      ,result,this.mainMenu.player);
    }//GEN-LAST:event_hardModeActionPerformed

    /**
     * @param args the command line arguments
     */

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyMode;
    private javax.swing.JButton hardMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton middleMode;
    // End of variables declaration//GEN-END:variables
}
